version: "3"

services:
  pg:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: db.env
    networks:
      - jaunty
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  jaunty:
    build:
      context: .
    depends_on: pg
    container_name: jaunty
    restart: unless-stopped
    env_file: .env
    networks:
      - jaunty
    ports:
      - "8080:8080"

networks:
  jaunty:
    external: true