version: "3"

services:
  pg:
    image: postgres
    container_name: pg
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - jaunty
  jaunty:
    image: ghcr.io/jaunty/jaunty:latest
    container_name: jaunty
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - jaunty

networks:
  jaunty:
    external: true