// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Bans          string
	DiscordTokens string
	Users         string
	Whitelist     string
}{
	Bans:          "bans",
	DiscordTokens: "discord_tokens",
	Users:         "users",
	Whitelist:     "whitelist",
}
