// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DiscordToken is an object representing the database table.
type DiscordToken struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	SF           string    `boil:"sf" json:"sf" toml:"sf" yaml:"sf"`
	AccessToken  string    `boil:"access_token" json:"access_token" toml:"access_token" yaml:"access_token"`
	TokenType    string    `boil:"token_type" json:"token_type" toml:"token_type" yaml:"token_type"`
	Expiry       time.Time `boil:"expiry" json:"expiry" toml:"expiry" yaml:"expiry"`
	RefreshToken string    `boil:"refresh_token" json:"refresh_token" toml:"refresh_token" yaml:"refresh_token"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *discordTokenR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L discordTokenL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DiscordTokenColumns = struct {
	ID           string
	SF           string
	AccessToken  string
	TokenType    string
	Expiry       string
	RefreshToken string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	SF:           "sf",
	AccessToken:  "access_token",
	TokenType:    "token_type",
	Expiry:       "expiry",
	RefreshToken: "refresh_token",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var DiscordTokenTableColumns = struct {
	ID           string
	SF           string
	AccessToken  string
	TokenType    string
	Expiry       string
	RefreshToken string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "discord_tokens.id",
	SF:           "discord_tokens.sf",
	AccessToken:  "discord_tokens.access_token",
	TokenType:    "discord_tokens.token_type",
	Expiry:       "discord_tokens.expiry",
	RefreshToken: "discord_tokens.refresh_token",
	CreatedAt:    "discord_tokens.created_at",
	UpdatedAt:    "discord_tokens.updated_at",
}

// Generated where

var DiscordTokenWhere = struct {
	ID           whereHelperint64
	SF           whereHelperstring
	AccessToken  whereHelperstring
	TokenType    whereHelperstring
	Expiry       whereHelpertime_Time
	RefreshToken whereHelperstring
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint64{field: "\"discord_tokens\".\"id\""},
	SF:           whereHelperstring{field: "\"discord_tokens\".\"sf\""},
	AccessToken:  whereHelperstring{field: "\"discord_tokens\".\"access_token\""},
	TokenType:    whereHelperstring{field: "\"discord_tokens\".\"token_type\""},
	Expiry:       whereHelpertime_Time{field: "\"discord_tokens\".\"expiry\""},
	RefreshToken: whereHelperstring{field: "\"discord_tokens\".\"refresh_token\""},
	CreatedAt:    whereHelpertime_Time{field: "\"discord_tokens\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"discord_tokens\".\"updated_at\""},
}

// DiscordTokenRels is where relationship names are stored.
var DiscordTokenRels = struct {
}{}

// discordTokenR is where relationships are stored.
type discordTokenR struct {
}

// NewStruct creates a new relationship struct
func (*discordTokenR) NewStruct() *discordTokenR {
	return &discordTokenR{}
}

// discordTokenL is where Load methods for each relationship are stored.
type discordTokenL struct{}

var (
	discordTokenAllColumns            = []string{"id", "sf", "access_token", "token_type", "expiry", "refresh_token", "created_at", "updated_at"}
	discordTokenColumnsWithoutDefault = []string{"sf", "access_token", "token_type", "expiry", "refresh_token"}
	discordTokenColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	discordTokenPrimaryKeyColumns     = []string{"id"}
)

type (
	// DiscordTokenSlice is an alias for a slice of pointers to DiscordToken.
	// This should almost always be used instead of []DiscordToken.
	DiscordTokenSlice []*DiscordToken

	discordTokenQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	discordTokenType                 = reflect.TypeOf(&DiscordToken{})
	discordTokenMapping              = queries.MakeStructMapping(discordTokenType)
	discordTokenPrimaryKeyMapping, _ = queries.BindMapping(discordTokenType, discordTokenMapping, discordTokenPrimaryKeyColumns)
	discordTokenInsertCacheMut       sync.RWMutex
	discordTokenInsertCache          = make(map[string]insertCache)
	discordTokenUpdateCacheMut       sync.RWMutex
	discordTokenUpdateCache          = make(map[string]updateCache)
	discordTokenUpsertCacheMut       sync.RWMutex
	discordTokenUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single discordToken record from the query.
func (q discordTokenQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DiscordToken, error) {
	o := &DiscordToken{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for discord_tokens")
	}

	return o, nil
}

// All returns all DiscordToken records from the query.
func (q discordTokenQuery) All(ctx context.Context, exec boil.ContextExecutor) (DiscordTokenSlice, error) {
	var o []*DiscordToken

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DiscordToken slice")
	}

	return o, nil
}

// Count returns the count of all DiscordToken records in the query.
func (q discordTokenQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count discord_tokens rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q discordTokenQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if discord_tokens exists")
	}

	return count > 0, nil
}

// DiscordTokens retrieves all the records using an executor.
func DiscordTokens(mods ...qm.QueryMod) discordTokenQuery {
	mods = append(mods, qm.From("\"discord_tokens\""))
	return discordTokenQuery{NewQuery(mods...)}
}

// FindDiscordToken retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDiscordToken(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*DiscordToken, error) {
	discordTokenObj := &DiscordToken{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"discord_tokens\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, discordTokenObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from discord_tokens")
	}

	return discordTokenObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DiscordToken) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no discord_tokens provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(discordTokenColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	discordTokenInsertCacheMut.RLock()
	cache, cached := discordTokenInsertCache[key]
	discordTokenInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			discordTokenAllColumns,
			discordTokenColumnsWithDefault,
			discordTokenColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(discordTokenType, discordTokenMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(discordTokenType, discordTokenMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"discord_tokens\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"discord_tokens\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into discord_tokens")
	}

	if !cached {
		discordTokenInsertCacheMut.Lock()
		discordTokenInsertCache[key] = cache
		discordTokenInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the DiscordToken.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DiscordToken) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	discordTokenUpdateCacheMut.RLock()
	cache, cached := discordTokenUpdateCache[key]
	discordTokenUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			discordTokenAllColumns,
			discordTokenPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update discord_tokens, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"discord_tokens\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, discordTokenPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(discordTokenType, discordTokenMapping, append(wl, discordTokenPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update discord_tokens row")
	}

	if !cached {
		discordTokenUpdateCacheMut.Lock()
		discordTokenUpdateCache[key] = cache
		discordTokenUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q discordTokenQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for discord_tokens")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DiscordTokenSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), discordTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"discord_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, discordTokenPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in discordToken slice")
	}

	return nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DiscordToken) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no discord_tokens provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(discordTokenColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	discordTokenUpsertCacheMut.RLock()
	cache, cached := discordTokenUpsertCache[key]
	discordTokenUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			discordTokenAllColumns,
			discordTokenColumnsWithDefault,
			discordTokenColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			discordTokenAllColumns,
			discordTokenPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert discord_tokens, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(discordTokenPrimaryKeyColumns))
			copy(conflict, discordTokenPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"discord_tokens\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(discordTokenType, discordTokenMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(discordTokenType, discordTokenMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert discord_tokens")
	}

	if !cached {
		discordTokenUpsertCacheMut.Lock()
		discordTokenUpsertCache[key] = cache
		discordTokenUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single DiscordToken record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DiscordToken) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no DiscordToken provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), discordTokenPrimaryKeyMapping)
	sql := "DELETE FROM \"discord_tokens\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from discord_tokens")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q discordTokenQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no discordTokenQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from discord_tokens")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DiscordTokenSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), discordTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"discord_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, discordTokenPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from discordToken slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DiscordToken) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDiscordToken(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DiscordTokenSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DiscordTokenSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), discordTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"discord_tokens\".* FROM \"discord_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, discordTokenPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DiscordTokenSlice")
	}

	*o = slice

	return nil
}

// DiscordTokenExists checks if the DiscordToken row exists.
func DiscordTokenExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"discord_tokens\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if discord_tokens exists")
	}

	return exists, nil
}
