// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Whitelist is an object representing the database table.
type Whitelist struct {
	ID              int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	SF              string    `boil:"sf" json:"sf" toml:"sf" yaml:"sf"`
	UUID            string    `boil:"uuid" json:"uuid" toml:"uuid" yaml:"uuid"`
	WhitelistStatus string    `boil:"whitelist_status" json:"whitelist_status" toml:"whitelist_status" yaml:"whitelist_status"`
	CreatedAt       time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *whitelistR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L whitelistL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WhitelistColumns = struct {
	ID              string
	SF              string
	UUID            string
	WhitelistStatus string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "id",
	SF:              "sf",
	UUID:            "uuid",
	WhitelistStatus: "whitelist_status",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}

var WhitelistTableColumns = struct {
	ID              string
	SF              string
	UUID            string
	WhitelistStatus string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "whitelist.id",
	SF:              "whitelist.sf",
	UUID:            "whitelist.uuid",
	WhitelistStatus: "whitelist.whitelist_status",
	CreatedAt:       "whitelist.created_at",
	UpdatedAt:       "whitelist.updated_at",
}

// Generated where

var WhitelistWhere = struct {
	ID              whereHelperint64
	SF              whereHelperstring
	UUID            whereHelperstring
	WhitelistStatus whereHelperstring
	CreatedAt       whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
}{
	ID:              whereHelperint64{field: "\"whitelist\".\"id\""},
	SF:              whereHelperstring{field: "\"whitelist\".\"sf\""},
	UUID:            whereHelperstring{field: "\"whitelist\".\"uuid\""},
	WhitelistStatus: whereHelperstring{field: "\"whitelist\".\"whitelist_status\""},
	CreatedAt:       whereHelpertime_Time{field: "\"whitelist\".\"created_at\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"whitelist\".\"updated_at\""},
}

// WhitelistRels is where relationship names are stored.
var WhitelistRels = struct {
}{}

// whitelistR is where relationships are stored.
type whitelistR struct {
}

// NewStruct creates a new relationship struct
func (*whitelistR) NewStruct() *whitelistR {
	return &whitelistR{}
}

// whitelistL is where Load methods for each relationship are stored.
type whitelistL struct{}

var (
	whitelistAllColumns            = []string{"id", "sf", "uuid", "whitelist_status", "created_at", "updated_at"}
	whitelistColumnsWithoutDefault = []string{"sf", "uuid"}
	whitelistColumnsWithDefault    = []string{"id", "whitelist_status", "created_at", "updated_at"}
	whitelistPrimaryKeyColumns     = []string{"id"}
)

type (
	// WhitelistSlice is an alias for a slice of pointers to Whitelist.
	// This should almost always be used instead of []Whitelist.
	WhitelistSlice []*Whitelist

	whitelistQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	whitelistType                 = reflect.TypeOf(&Whitelist{})
	whitelistMapping              = queries.MakeStructMapping(whitelistType)
	whitelistPrimaryKeyMapping, _ = queries.BindMapping(whitelistType, whitelistMapping, whitelistPrimaryKeyColumns)
	whitelistInsertCacheMut       sync.RWMutex
	whitelistInsertCache          = make(map[string]insertCache)
	whitelistUpdateCacheMut       sync.RWMutex
	whitelistUpdateCache          = make(map[string]updateCache)
	whitelistUpsertCacheMut       sync.RWMutex
	whitelistUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single whitelist record from the query.
func (q whitelistQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Whitelist, error) {
	o := &Whitelist{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for whitelist")
	}

	return o, nil
}

// All returns all Whitelist records from the query.
func (q whitelistQuery) All(ctx context.Context, exec boil.ContextExecutor) (WhitelistSlice, error) {
	var o []*Whitelist

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Whitelist slice")
	}

	return o, nil
}

// Count returns the count of all Whitelist records in the query.
func (q whitelistQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count whitelist rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q whitelistQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if whitelist exists")
	}

	return count > 0, nil
}

// Whitelists retrieves all the records using an executor.
func Whitelists(mods ...qm.QueryMod) whitelistQuery {
	mods = append(mods, qm.From("\"whitelist\""))
	return whitelistQuery{NewQuery(mods...)}
}

// FindWhitelist retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWhitelist(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Whitelist, error) {
	whitelistObj := &Whitelist{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"whitelist\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, whitelistObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from whitelist")
	}

	return whitelistObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Whitelist) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no whitelist provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(whitelistColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	whitelistInsertCacheMut.RLock()
	cache, cached := whitelistInsertCache[key]
	whitelistInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			whitelistAllColumns,
			whitelistColumnsWithDefault,
			whitelistColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(whitelistType, whitelistMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(whitelistType, whitelistMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"whitelist\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"whitelist\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into whitelist")
	}

	if !cached {
		whitelistInsertCacheMut.Lock()
		whitelistInsertCache[key] = cache
		whitelistInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Whitelist.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Whitelist) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	whitelistUpdateCacheMut.RLock()
	cache, cached := whitelistUpdateCache[key]
	whitelistUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			whitelistAllColumns,
			whitelistPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update whitelist, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"whitelist\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, whitelistPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(whitelistType, whitelistMapping, append(wl, whitelistPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update whitelist row")
	}

	if !cached {
		whitelistUpdateCacheMut.Lock()
		whitelistUpdateCache[key] = cache
		whitelistUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q whitelistQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for whitelist")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WhitelistSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), whitelistPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"whitelist\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, whitelistPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in whitelist slice")
	}

	return nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Whitelist) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no whitelist provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(whitelistColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	whitelistUpsertCacheMut.RLock()
	cache, cached := whitelistUpsertCache[key]
	whitelistUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			whitelistAllColumns,
			whitelistColumnsWithDefault,
			whitelistColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			whitelistAllColumns,
			whitelistPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert whitelist, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(whitelistPrimaryKeyColumns))
			copy(conflict, whitelistPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"whitelist\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(whitelistType, whitelistMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(whitelistType, whitelistMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert whitelist")
	}

	if !cached {
		whitelistUpsertCacheMut.Lock()
		whitelistUpsertCache[key] = cache
		whitelistUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Whitelist record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Whitelist) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no Whitelist provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), whitelistPrimaryKeyMapping)
	sql := "DELETE FROM \"whitelist\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from whitelist")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q whitelistQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no whitelistQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from whitelist")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WhitelistSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), whitelistPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"whitelist\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, whitelistPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from whitelist slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Whitelist) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWhitelist(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WhitelistSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WhitelistSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), whitelistPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"whitelist\".* FROM \"whitelist\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, whitelistPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WhitelistSlice")
	}

	*o = slice

	return nil
}

// WhitelistExists checks if the Whitelist row exists.
func WhitelistExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"whitelist\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if whitelist exists")
	}

	return exists, nil
}
