name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Version
      run: |
        JAUNTY_VERSION="r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
        echo Version $JAUNTY_VERSION
        echo JAUNTY_VERSION=$JAUNTY_VERSION >> $GITHUB_ENV
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Tidy modules
      run: go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2

    - name: Turnstyle
      if: ${{ github.event_name == 'push' && github.ref == 'refs/head/trunk' }}
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Image
      run: docker build --file Dockerfile --tag jaunty:latest --tag jaunty:${{ env.JAUNTY_VERSION}} --build-arg version=${{ env.JAUNTY_VERSION }} .
    
    - name: Push to GitHub
      if: ${{ github.repository == 'jaunty/jaunty' && github.event_name == 'push' && github.ref == 'refs/heads/trunk' }}
      run: |
        echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker tag jaunty:latest ghcr.io/jaunty/jaunty:latest
        docker tag jaunty:${{ env.JAUNTY_VERSION }} ghcr.io/jaunty/jaunty:${{ env.JAUNTY_VERSION }}
        docker push ghcr.io/jaunty/jaunty:latest
        docker push ghcr.io/jaunty/jaunty:${{ env.JAUNTY_VERSION }} 
