// Code generated by qtc from "account_delete.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/account_delete.qtpl:1
package templates

//line internal/web/templates/account_delete.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/account_delete.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/account_delete.qtpl:2
type AccountDeletePage struct {
	*BasePage
}

//line internal/web/templates/account_delete.qtpl:7
func (p *AccountDeletePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/account_delete.qtpl:7
	qw422016.N().S(`Account Deletion`)
//line internal/web/templates/account_delete.qtpl:7
}

//line internal/web/templates/account_delete.qtpl:7
func (p *AccountDeletePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/account_delete.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/account_delete.qtpl:7
	p.StreamTitle(qw422016)
//line internal/web/templates/account_delete.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/account_delete.qtpl:7
}

//line internal/web/templates/account_delete.qtpl:7
func (p *AccountDeletePage) Title() string {
//line internal/web/templates/account_delete.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/account_delete.qtpl:7
	p.WriteTitle(qb422016)
//line internal/web/templates/account_delete.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/web/templates/account_delete.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/account_delete.qtpl:7
	return qs422016
//line internal/web/templates/account_delete.qtpl:7
}

//line internal/web/templates/account_delete.qtpl:9
func (p *AccountDeletePage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/account_delete.qtpl:9
	qw422016.N().S(`
<div class="columns is-centered">
    <div class="column is-narrow has-text-centered">
        <h1 class="title">SO YOU WANT TO DELETE YOUR ACCOUNT</h1>
        <h2 class="subtitle">Your Jaunty account, I mean. Your Discord account will be fine.</h2>
        <hr class="mb-1">
    </div>
</div>
<div class="columns is-centered">
    <div class="column is-narrow has-text-centered">
        <form method="POST">
            <div class="field">
                <div class="control">
                    <label class="checkbox">
                    <input type="checkbox" required>
                    I understand that this is irreversible
                    </label>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <label class="checkbox">
                    <input type="checkbox" required>
                    I REALLY understand that this is irreversible
                    </label>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <label class="checkbox">
                    <input type="checkbox" required>
                    I TRIPLE OMEGA SUPER UBER UNDERSTAND that this is irreversible
                    </label>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <label class="checkbox">
                    <input type="checkbox" required>
                    I understand that I will be removed from the Jaunty Discord upon account deletion
                    </label>
                </div>
            </div>

            <div class="field">
                <div class="control">
                     <input type="submit" class="button is-jaunty" value="Delete">
                </div>
            </div>
        </form>
    </div>
</div>
`)
//line internal/web/templates/account_delete.qtpl:64
}

//line internal/web/templates/account_delete.qtpl:64
func (p *AccountDeletePage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/account_delete.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/account_delete.qtpl:64
	p.StreamBody(qw422016)
//line internal/web/templates/account_delete.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/account_delete.qtpl:64
}

//line internal/web/templates/account_delete.qtpl:64
func (p *AccountDeletePage) Body() string {
//line internal/web/templates/account_delete.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/account_delete.qtpl:64
	p.WriteBody(qb422016)
//line internal/web/templates/account_delete.qtpl:64
	qs422016 := string(qb422016.B)
//line internal/web/templates/account_delete.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/account_delete.qtpl:64
	return qs422016
//line internal/web/templates/account_delete.qtpl:64
}
