// Code generated by qtc from "banned.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/banned.qtpl:1
package templates

//line internal/web/templates/banned.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/banned.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/banned.qtpl:1
type BannedPage struct {
	*BasePage
}

//line internal/web/templates/banned.qtpl:7
func (p *BannedPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/banned.qtpl:7
	qw422016.N().S(`BANNED`)
//line internal/web/templates/banned.qtpl:7
}

//line internal/web/templates/banned.qtpl:7
func (p *BannedPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/banned.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/banned.qtpl:7
	p.StreamTitle(qw422016)
//line internal/web/templates/banned.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/banned.qtpl:7
}

//line internal/web/templates/banned.qtpl:7
func (p *BannedPage) Title() string {
//line internal/web/templates/banned.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/banned.qtpl:7
	p.WriteTitle(qb422016)
//line internal/web/templates/banned.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/web/templates/banned.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/banned.qtpl:7
	return qs422016
//line internal/web/templates/banned.qtpl:7
}

//line internal/web/templates/banned.qtpl:9
func (p *BannedPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/banned.qtpl:9
	qw422016.N().S(`
<section class="hero is-large">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">You are banned from Jaunty.</h1>
            <h2 class="subtitle">If you believe this in error, contact holedaemon.</h2>
        </div>
    </div>
</section>
`)
//line internal/web/templates/banned.qtpl:18
}

//line internal/web/templates/banned.qtpl:18
func (p *BannedPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/banned.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/banned.qtpl:18
	p.StreamBody(qw422016)
//line internal/web/templates/banned.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/banned.qtpl:18
}

//line internal/web/templates/banned.qtpl:18
func (p *BannedPage) Body() string {
//line internal/web/templates/banned.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/banned.qtpl:18
	p.WriteBody(qb422016)
//line internal/web/templates/banned.qtpl:18
	qs422016 := string(qb422016.B)
//line internal/web/templates/banned.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/banned.qtpl:18
	return qs422016
//line internal/web/templates/banned.qtpl:18
}
