// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/base.qtpl:1
package templates

//line internal/web/templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/base.qtpl:1
type Page interface {
//line internal/web/templates/base.qtpl:1
	Title() string
//line internal/web/templates/base.qtpl:1
	StreamTitle(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:1
	WriteTitle(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:1
	Meta() string
//line internal/web/templates/base.qtpl:1
	StreamMeta(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:1
	WriteMeta(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:1
	Body() string
//line internal/web/templates/base.qtpl:1
	StreamBody(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:1
	WriteBody(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:1
}

//line internal/web/templates/base.qtpl:8
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line internal/web/templates/base.qtpl:8
	qw422016.N().S(`
<!DOCTYPE html>
<html>
    <head>
        <title>`)
//line internal/web/templates/base.qtpl:12
	p.StreamTitle(qw422016)
//line internal/web/templates/base.qtpl:12
	qw422016.N().S(` &bull; Jaunty</title>

        <link rel="stylesheet" href="/static/jaunty.css">

        `)
//line internal/web/templates/base.qtpl:16
	p.StreamMeta(qw422016)
//line internal/web/templates/base.qtpl:16
	qw422016.N().S(`
    </head>
    <body>
        <nav class="navbar is-jaunty mb-5">
            <div class="container">
                <div class="navbar-brand is-size-5">
                    <a class="navbar-item" href="/">ᕕ(՞ᗜ՞)ᕗ</a>
                </div>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>

                <div class="navbar-menu">
                    <div class="navbar-start">
                        <a class="navbar-item" href="/join">
                            Join
                        </a>
                    </div>
                </div>
            </div>
        </nav>

        `)
//line internal/web/templates/base.qtpl:41
	p.StreamBody(qw422016)
//line internal/web/templates/base.qtpl:41
	qw422016.N().S(`
    </body>
</html>
`)
//line internal/web/templates/base.qtpl:44
}

//line internal/web/templates/base.qtpl:44
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line internal/web/templates/base.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:44
	StreamPageTemplate(qw422016, p)
//line internal/web/templates/base.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:44
}

//line internal/web/templates/base.qtpl:44
func PageTemplate(p Page) string {
//line internal/web/templates/base.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:44
	WritePageTemplate(qb422016, p)
//line internal/web/templates/base.qtpl:44
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:44
	return qs422016
//line internal/web/templates/base.qtpl:44
}

//line internal/web/templates/base.qtpl:46
type BasePage struct{}

//line internal/web/templates/base.qtpl:47
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:47
	qw422016.N().S(`Jaunty`)
//line internal/web/templates/base.qtpl:47
}

//line internal/web/templates/base.qtpl:47
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:47
	p.StreamTitle(qw422016)
//line internal/web/templates/base.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:47
}

//line internal/web/templates/base.qtpl:47
func (p *BasePage) Title() string {
//line internal/web/templates/base.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:47
	p.WriteTitle(qb422016)
//line internal/web/templates/base.qtpl:47
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:47
	return qs422016
//line internal/web/templates/base.qtpl:47
}

//line internal/web/templates/base.qtpl:48
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:48
}

//line internal/web/templates/base.qtpl:48
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:48
	p.StreamBody(qw422016)
//line internal/web/templates/base.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:48
}

//line internal/web/templates/base.qtpl:48
func (p *BasePage) Body() string {
//line internal/web/templates/base.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:48
	p.WriteBody(qb422016)
//line internal/web/templates/base.qtpl:48
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:48
	return qs422016
//line internal/web/templates/base.qtpl:48
}

//line internal/web/templates/base.qtpl:49
func (p *BasePage) StreamMeta(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:49
}

//line internal/web/templates/base.qtpl:49
func (p *BasePage) WriteMeta(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:49
	p.StreamMeta(qw422016)
//line internal/web/templates/base.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:49
}

//line internal/web/templates/base.qtpl:49
func (p *BasePage) Meta() string {
//line internal/web/templates/base.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:49
	p.WriteMeta(qb422016)
//line internal/web/templates/base.qtpl:49
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:49
	return qs422016
//line internal/web/templates/base.qtpl:49
}
