// Code generated by qtc from "cancel_request.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:1
package templates

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:1
import (
	"github.com/jaunty/jaunty/internal/database/models"
)

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:7
type CancelRequestPage struct {
	*BasePage
	Request *models.Whitelist
}

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
func (p *CancelRequestPage) StreamTitle(qw422016 *qt422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	qw422016.N().S(`Cancel Request`)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
}

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
func (p *CancelRequestPage) WriteTitle(qq422016 qtio422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	p.StreamTitle(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
}

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
func (p *CancelRequestPage) Title() string {
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	p.WriteTitle(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	qs422016 := string(qb422016.B)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
	return qs422016
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:13
}

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:15
func (p *CancelRequestPage) StreamBody(qw422016 *qt422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:15
	qw422016.N().S(`
<div class="columns is-centered">
    <div class="column is-narrow">
        <h1 class="title">Just making sure you want to do that, Star Fox</h1>
        <hr>
    </div>
    <div class="column is-narrow">
        <form method="POST">
            <div class="field">
                <div class="control">
                    <label class="checkbox">
                    <input type="checkbox" required>
                    Yeah, let's rock
                    </label>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input type="submit" class="button is-jaunty" value="Punch it">
                </div>
            </div>
        </form>
    </div>
</div>
`)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
}

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
func (p *CancelRequestPage) WriteBody(qq422016 qtio422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	p.StreamBody(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
}

//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
func (p *CancelRequestPage) Body() string {
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	p.WriteBody(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	qs422016 := string(qb422016.B)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
	return qs422016
//line /home/max/git/jaunty/redux/internal/web/templates/cancel_request.qtpl:40
}
