// Code generated by qtc from "dashboard.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:2
package templates

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:2
import (
	"github.com/jaunty/jaunty/internal/database/models"

	"time"
)

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:10
var (
	loc *time.Location
	err error
)

func init() {
	loc, err = time.LoadLocation("EST")
	if err != nil {
		panic(err)
	}
}

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:24
type DashboardPage struct {
	*BasePage
	Requests      []*models.Whitelist
	ResolvedUUIDs map[string]string
}

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
func (p *DashboardPage) StreamTitle(qw422016 *qt422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	qw422016.N().S(`Dashboard`)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
}

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
func (p *DashboardPage) WriteTitle(qq422016 qtio422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	p.StreamTitle(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
}

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
func (p *DashboardPage) Title() string {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	p.WriteTitle(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	qs422016 := string(qb422016.B)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
	return qs422016
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:31
}

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:33
func (p *DashboardPage) StreamBody(qw422016 *qt422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:33
	qw422016.N().S(`
<div class="container">
    <div class="block">
        <h1 class="title">Make Your Peace</h1>
        <h2 class="subtitle">Account configuration stuff</h2>
    </div>

    <div class="field is-grouped mb-5">
        <p class="control">
            <a href="/account/delete" class="button is-jaunty">
                Account Deletion
            </a>
        </p>
    </div>

    <div class="mb-6">
        <h1 class="title">Whitelist Requests</h1>
        <h2 class="subtitle">Every single whitelist request you've ever made, all right here.</h2>
    </div>

    `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:53
	if len(p.Requests) == 0 {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:53
		qw422016.N().S(`
        <div>
            <h1 class="title">Literally none.</h1>
            <h2 class="subtitle">Ok.</h2>
        </div>
    `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:58
	} else {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:58
		qw422016.N().S(`
        <div class="columns">
            `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:60
		for _, wr := range p.Requests {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:60
			qw422016.N().S(`
                <div class="column is-narrow box">
                    <ul class="is-size-5">
                        <li>`)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:63
			qw422016.E().S(p.ResolvedUUIDs[wr.UUID])
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:63
			qw422016.N().S(`</li>
                        <li>`)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:64
			qw422016.E().S(wr.CreatedAt.In(loc).Format("01/02/2006 03:04pm"))
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:64
			qw422016.N().S(`</li>
                        <li>
                            <span class="tag is-uppercase
`)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:67
			switch wr.WhitelistStatus {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:68
			case "pending":
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:68
				qw422016.N().S(`
                                    is-warning
                                `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:70
			case "approved":
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:70
				qw422016.N().S(`
                                    is-success
                                `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:72
			case "rejected":
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:72
				qw422016.N().S(`
                                    is-danger
`)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:74
			}
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:74
			qw422016.N().S(`                                ">
                                `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:76
			qw422016.E().S(wr.WhitelistStatus)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:76
			qw422016.N().S(`
                            </span>
                        </li>
                    </ul>
            `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:80
		}
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:80
		qw422016.N().S(`
        </div>
    `)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:82
	}
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:82
	qw422016.N().S(`
</div>
`)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
}

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
func (p *DashboardPage) WriteBody(qq422016 qtio422016.Writer) {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	p.StreamBody(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
}

//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
func (p *DashboardPage) Body() string {
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	p.WriteBody(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	qs422016 := string(qb422016.B)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
	return qs422016
//line /home/max/git/jaunty/redux/internal/web/templates/dashboard.qtpl:84
}
