// Code generated by qtc from "delete_request.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/delete_request.qtpl:1
package templates

//line internal/web/templates/delete_request.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/delete_request.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/delete_request.qtpl:2
type DeleteRequestPage struct {
	*BasePage
}

//line internal/web/templates/delete_request.qtpl:7
func (p *DeleteRequestPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/delete_request.qtpl:7
	qw422016.N().S(`Delete Request`)
//line internal/web/templates/delete_request.qtpl:7
}

//line internal/web/templates/delete_request.qtpl:7
func (p *DeleteRequestPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/delete_request.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/delete_request.qtpl:7
	p.StreamTitle(qw422016)
//line internal/web/templates/delete_request.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/delete_request.qtpl:7
}

//line internal/web/templates/delete_request.qtpl:7
func (p *DeleteRequestPage) Title() string {
//line internal/web/templates/delete_request.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/delete_request.qtpl:7
	p.WriteTitle(qb422016)
//line internal/web/templates/delete_request.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/web/templates/delete_request.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/delete_request.qtpl:7
	return qs422016
//line internal/web/templates/delete_request.qtpl:7
}

//line internal/web/templates/delete_request.qtpl:9
func (p *DeleteRequestPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/delete_request.qtpl:9
	qw422016.N().S(`
<div class="columns is-centered">
    <div class="column is-narrow">
        <h1 class="title">Just making sure you want to do that, Star Fox</h1>
        <hr class="mb-1>
    </div>
</div>
<div class="columns is-centered">
    <div class="column is-narrow has-text-centered">
        <form method="POST">
            <div class="field">
                <div class="control">
                    <label class="checkbox">
                    <input type="checkbox" required>
                    Yeah, let's rock
                    </label>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input type="submit" class="button is-jaunty" value="Punch it">
                </div>
            </div>
        </form>
    </div>
</div>
`)
//line internal/web/templates/delete_request.qtpl:36
}

//line internal/web/templates/delete_request.qtpl:36
func (p *DeleteRequestPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/delete_request.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/delete_request.qtpl:36
	p.StreamBody(qw422016)
//line internal/web/templates/delete_request.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/delete_request.qtpl:36
}

//line internal/web/templates/delete_request.qtpl:36
func (p *DeleteRequestPage) Body() string {
//line internal/web/templates/delete_request.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/delete_request.qtpl:36
	p.WriteBody(qb422016)
//line internal/web/templates/delete_request.qtpl:36
	qs422016 := string(qb422016.B)
//line internal/web/templates/delete_request.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/delete_request.qtpl:36
	return qs422016
//line internal/web/templates/delete_request.qtpl:36
}
