// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/index.qtpl:1
package templates

//line internal/web/templates/index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/index.qtpl:2
type IndexPage struct {
	*BasePage
}

//line internal/web/templates/index.qtpl:7
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/index.qtpl:7
	qw422016.N().S(`Home`)
//line internal/web/templates/index.qtpl:7
}

//line internal/web/templates/index.qtpl:7
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/index.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:7
	p.StreamTitle(qw422016)
//line internal/web/templates/index.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:7
}

//line internal/web/templates/index.qtpl:7
func (p *IndexPage) Title() string {
//line internal/web/templates/index.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:7
	p.WriteTitle(qb422016)
//line internal/web/templates/index.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:7
	return qs422016
//line internal/web/templates/index.qtpl:7
}

//line internal/web/templates/index.qtpl:9
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/index.qtpl:9
	qw422016.N().S(`
<div class="container">
            <div class="columns is-centered">
                <div class="column is-one-third has-text-centered">
                    <h1 class="title">Welcome to Jaunty!</h1>
                    <hr>
                </div>
            </div>
            <div class="columns is-centered">
                <div class="column is-half has-text-centered is-size-5">
                    <p class="block">Jaunty is a Minecraft server community dedicated to providing friends of <a href="https://twitter.com/holedaemon" target="_blank">holedaemon</a> a lax, inclusive place to play the latest Minecraft updates.</p>

                    <p class="block">
                        Anyone is free to request whitelist, but only those that have prior approval are guaranteed to be accepted.
                    </p>

                    <div class="block">
                        <p>Approval is more less limited to the following:</p>
                        <ul style="list-style: square;">
                            <li>You are a friend, mutual, or have otherwise been invited by holedaemon</li>
                            <li>You have been invited by an existing member of Jaunty that has vouched for you to holedaemon</li>
                        </ul>
                    </div>

                    <p class="block">
                        These requirements may seem strict, but they're in place purely just to keep assholes out.
                    </p>

                    <p class="block">
                        Click <a href="/join">here</a> to submit a whitelist request.
                    </p>
                </div>
            </div>
        </div>
`)
//line internal/web/templates/index.qtpl:43
}

//line internal/web/templates/index.qtpl:43
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/index.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/index.qtpl:43
	p.StreamBody(qw422016)
//line internal/web/templates/index.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/index.qtpl:43
}

//line internal/web/templates/index.qtpl:43
func (p *IndexPage) Body() string {
//line internal/web/templates/index.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/index.qtpl:43
	p.WriteBody(qb422016)
//line internal/web/templates/index.qtpl:43
	qs422016 := string(qb422016.B)
//line internal/web/templates/index.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/index.qtpl:43
	return qs422016
//line internal/web/templates/index.qtpl:43
}
