// Code generated by qtc from "join.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/join.qtpl:1
package templates

//line internal/web/templates/join.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/join.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/join.qtpl:2
type JoinPage struct {
	*BasePage
}

//line internal/web/templates/join.qtpl:7
func (p *JoinPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/join.qtpl:7
	qw422016.N().S(`Join`)
//line internal/web/templates/join.qtpl:7
}

//line internal/web/templates/join.qtpl:7
func (p *JoinPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/join.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/join.qtpl:7
	p.StreamTitle(qw422016)
//line internal/web/templates/join.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/join.qtpl:7
}

//line internal/web/templates/join.qtpl:7
func (p *JoinPage) Title() string {
//line internal/web/templates/join.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/join.qtpl:7
	p.WriteTitle(qb422016)
//line internal/web/templates/join.qtpl:7
	qs422016 := string(qb422016.B)
//line internal/web/templates/join.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/join.qtpl:7
	return qs422016
//line internal/web/templates/join.qtpl:7
}

//line internal/web/templates/join.qtpl:9
func (p *JoinPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/join.qtpl:9
	qw422016.N().S(`
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <h1 class="title">Check Yourself Before You Whitelist Yourself</h1>
                <hr>
            </div>
        </div>

        <div class="columns is-centered">
            <div class="column is-one-third">
                <form action="" method="POST">
                    <div class="field has-addons has-addons-centered">
                        <div class="control">
                            <input id="username" name="username" class="input" type="text" placeholder="Minecraft Username">
                        </div>
                        <div class="control">
                            <input for="username" type="submit" class="button is-jaunty" value="Submit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
`)
//line internal/web/templates/join.qtpl:33
}

//line internal/web/templates/join.qtpl:33
func (p *JoinPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/join.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/join.qtpl:33
	p.StreamBody(qw422016)
//line internal/web/templates/join.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/join.qtpl:33
}

//line internal/web/templates/join.qtpl:33
func (p *JoinPage) Body() string {
//line internal/web/templates/join.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/join.qtpl:33
	p.WriteBody(qb422016)
//line internal/web/templates/join.qtpl:33
	qs422016 := string(qb422016.B)
//line internal/web/templates/join.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/join.qtpl:33
	return qs422016
//line internal/web/templates/join.qtpl:33
}
