// Code generated by qtc from "new_request.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/new_request.qtpl:1
package templates

//line internal/web/templates/new_request.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/new_request.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/new_request.qtpl:2
type NewRequestPage struct {
	*BasePage
	Username string
}

//line internal/web/templates/new_request.qtpl:8
func (p *NewRequestPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/new_request.qtpl:8
	qw422016.N().S(`Request submitted`)
//line internal/web/templates/new_request.qtpl:8
}

//line internal/web/templates/new_request.qtpl:8
func (p *NewRequestPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/new_request.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/new_request.qtpl:8
	p.StreamTitle(qw422016)
//line internal/web/templates/new_request.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/new_request.qtpl:8
}

//line internal/web/templates/new_request.qtpl:8
func (p *NewRequestPage) Title() string {
//line internal/web/templates/new_request.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/new_request.qtpl:8
	p.WriteTitle(qb422016)
//line internal/web/templates/new_request.qtpl:8
	qs422016 := string(qb422016.B)
//line internal/web/templates/new_request.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/new_request.qtpl:8
	return qs422016
//line internal/web/templates/new_request.qtpl:8
}

//line internal/web/templates/new_request.qtpl:10
func (p *NewRequestPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/new_request.qtpl:10
	qw422016.N().S(`
    `)
//line internal/web/templates/new_request.qtpl:11
	if p.BasePage.User == nil {
//line internal/web/templates/new_request.qtpl:11
		qw422016.N().S(`
        <div class="modal is-active">
            <div class="modal-background"></div>
            <div class="modal-content">
                <h1 class="title">You shouldn't be here</h1>
                <h2 class="subtitle">Best head back the way you came</h2>
            </div>
        </div>
    `)
//line internal/web/templates/new_request.qtpl:19
	} else {
//line internal/web/templates/new_request.qtpl:19
		qw422016.N().S(`
        <div class="columns is-centered">
            <div class="column is-half" has-text-centered>
                <h1 class="title">Request Submitted</h1>
                <h2 class="subtitle">Keep an eye on the Discord for updates!</h2>
            </div>
        </div>
    `)
//line internal/web/templates/new_request.qtpl:26
	}
//line internal/web/templates/new_request.qtpl:26
	qw422016.N().S(`
`)
//line internal/web/templates/new_request.qtpl:27
}

//line internal/web/templates/new_request.qtpl:27
func (p *NewRequestPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/new_request.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/new_request.qtpl:27
	p.StreamBody(qw422016)
//line internal/web/templates/new_request.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/new_request.qtpl:27
}

//line internal/web/templates/new_request.qtpl:27
func (p *NewRequestPage) Body() string {
//line internal/web/templates/new_request.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/new_request.qtpl:27
	p.WriteBody(qb422016)
//line internal/web/templates/new_request.qtpl:27
	qs422016 := string(qb422016.B)
//line internal/web/templates/new_request.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/new_request.qtpl:27
	return qs422016
//line internal/web/templates/new_request.qtpl:27
}
