// Code generated by qtc from "success.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/success.qtpl:1
package templates

//line internal/web/templates/success.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/success.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/success.qtpl:2
type SuccessPage struct {
	*BasePage
	PageTitle string
	Header    string
	SubHeader string
}

//line internal/web/templates/success.qtpl:10
func (p *SuccessPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/success.qtpl:10
	qw422016.N().S(`
`)
//line internal/web/templates/success.qtpl:11
	if p.PageTitle == "" {
//line internal/web/templates/success.qtpl:11
		qw422016.N().S(`        Success
    `)
//line internal/web/templates/success.qtpl:13
	} else {
//line internal/web/templates/success.qtpl:13
		qw422016.N().S(`
        `)
//line internal/web/templates/success.qtpl:14
		qw422016.E().S(p.PageTitle)
//line internal/web/templates/success.qtpl:14
		qw422016.N().S(`
`)
//line internal/web/templates/success.qtpl:15
	}
//line internal/web/templates/success.qtpl:16
}

//line internal/web/templates/success.qtpl:16
func (p *SuccessPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/success.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/success.qtpl:16
	p.StreamTitle(qw422016)
//line internal/web/templates/success.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/success.qtpl:16
}

//line internal/web/templates/success.qtpl:16
func (p *SuccessPage) Title() string {
//line internal/web/templates/success.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/success.qtpl:16
	p.WriteTitle(qb422016)
//line internal/web/templates/success.qtpl:16
	qs422016 := string(qb422016.B)
//line internal/web/templates/success.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/success.qtpl:16
	return qs422016
//line internal/web/templates/success.qtpl:16
}

//line internal/web/templates/success.qtpl:18
func (p *SuccessPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/success.qtpl:18
	qw422016.N().S(`
    <div class="columns is-centered">
        <div class="column is-narrow has-text-centered">
            <h1 class="title">`)
//line internal/web/templates/success.qtpl:21
	qw422016.E().S(p.Header)
//line internal/web/templates/success.qtpl:21
	qw422016.N().S(`</h1>
            <h2 class="subtitle">`)
//line internal/web/templates/success.qtpl:22
	qw422016.E().S(p.SubHeader)
//line internal/web/templates/success.qtpl:22
	qw422016.N().S(`</h2>
        </div>
    </div>
`)
//line internal/web/templates/success.qtpl:25
}

//line internal/web/templates/success.qtpl:25
func (p *SuccessPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/success.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/success.qtpl:25
	p.StreamBody(qw422016)
//line internal/web/templates/success.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/success.qtpl:25
}

//line internal/web/templates/success.qtpl:25
func (p *SuccessPage) Body() string {
//line internal/web/templates/success.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/success.qtpl:25
	p.WriteBody(qb422016)
//line internal/web/templates/success.qtpl:25
	qs422016 := string(qb422016.B)
//line internal/web/templates/success.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/success.qtpl:25
	return qs422016
//line internal/web/templates/success.qtpl:25
}
